BEGIN;

ALTER TABLE "user" DISABLE ROW LEVEL SECURITY;

ALTER TABLE "session" DISABLE ROW LEVEL SECURITY;

ALTER TABLE "account" DISABLE ROW LEVEL SECURITY;

ALTER TABLE "verification" DISABLE ROW LEVEL SECURITY;

ALTER TABLE "jwks" DISABLE ROW LEVEL SECURITY;

COMMIT;