BEGIN;

DROP TABLE IF EXISTS "jwks" CASCADE;
DROP TABLE IF EXISTS "verification" CASCADE;
DROP TABLE IF EXISTS "account" CASCADE;
DROP TABLE IF EXISTS "session" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP EXTENSION IF EXISTS pgcrypto;

COMMIT;
