// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_accounts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO
    "account" (
        "userId",
        "accountId",
        "providerId",
        password
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, "userId", "accountId", "providerId", "accessToken", "refreshToken", "accessTokenExpiresAt", "refreshTokenExpiresAt", scope, "idToken", password, "createdAt", "updatedAt"
`

type CreateAccountParams struct {
	UserId     uuid.UUID `json:"userId"`
	AccountId  string    `json:"accountId"`
	ProviderId string    `json:"providerId"`
	Password   *string   `json:"password"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserId,
		arg.AccountId,
		arg.ProviderId,
		arg.Password,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.AccountId,
		&i.ProviderId,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IdToken,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountWithId = `-- name: CreateAccountWithId :one
INSERT INTO
    "account" (
        id,
        "userId",
        "accountId",
        "providerId",
        password
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, "userId", "accountId", "providerId", "accessToken", "refreshToken", "accessTokenExpiresAt", "refreshTokenExpiresAt", scope, "idToken", password, "createdAt", "updatedAt"
`

type CreateAccountWithIdParams struct {
	ID         uuid.UUID `json:"id"`
	UserId     uuid.UUID `json:"userId"`
	AccountId  string    `json:"accountId"`
	ProviderId string    `json:"providerId"`
	Password   *string   `json:"password"`
}

func (q *Queries) CreateAccountWithId(ctx context.Context, arg CreateAccountWithIdParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccountWithId,
		arg.ID,
		arg.UserId,
		arg.AccountId,
		arg.ProviderId,
		arg.Password,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.AccountId,
		&i.ProviderId,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IdToken,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM "account" WHERE id = $1 RETURNING id, "userId", "accountId", "providerId", "accessToken", "refreshToken", "accessTokenExpiresAt", "refreshTokenExpiresAt", scope, "idToken", password, "createdAt", "updatedAt"
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, deleteAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.AccountId,
		&i.ProviderId,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IdToken,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, "userId", "accountId", "providerId", "accessToken", "refreshToken", "accessTokenExpiresAt", "refreshTokenExpiresAt", scope, "idToken", password, "createdAt", "updatedAt" FROM "account" WHERE id = $1
`

func (q *Queries) GetAccountById(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.AccountId,
		&i.ProviderId,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IdToken,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserIdAndProvider = `-- name: GetAccountByUserIdAndProvider :one
SELECT id, "userId", "accountId", "providerId", "accessToken", "refreshToken", "accessTokenExpiresAt", "refreshTokenExpiresAt", scope, "idToken", password, "createdAt", "updatedAt" FROM "account" WHERE "userId" = $1 AND "providerId" = $2
`

type GetAccountByUserIdAndProviderParams struct {
	UserId     uuid.UUID `json:"userId"`
	ProviderId string    `json:"providerId"`
}

func (q *Queries) GetAccountByUserIdAndProvider(ctx context.Context, arg GetAccountByUserIdAndProviderParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserIdAndProvider, arg.UserId, arg.ProviderId)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.AccountId,
		&i.ProviderId,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.IdToken,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
