// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_sessions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one


INSERT INTO
    "session" (
        token,
        "userId",
        "expiresAt",
        "ipAddress",
        "userAgent"
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, "userId", token, "expiresAt", "ipAddress", "userAgent", "createdAt", "updatedAt"
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserId    uuid.UUID `json:"userId"`
	ExpiresAt time.Time `json:"expiresAt"`
	IpAddress *string   `json:"ipAddress"`
	UserAgent *string   `json:"userAgent"`
}

// CreateSession(ctx context.Context, session *Session) error
// GetSession(ctx context.Context, token string) (*Session, error)
// UpdateSession(ctx context.Context, token string, updates map[string]any) error
// DeleteSession(ctx context.Context, token string) error
// DeleteUserSessions(ctx context.Context, userID string) error
// Sessions table
// CREATE TABLE "session" (
//
//	id UUID PRIMARY KEY,
//	token VARCHAR(255) UNIQUE NOT NULL,
//	user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
//	expires_at TIMESTAMPTZ NOT NULL,
//	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
//	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
//	ip_address VARCHAR(45) NOT NULL,
//	user_agent VARCHAR NOT NULL,
//	impersonated_by UUID REFERENCES users (id)
//
// );
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Token,
		arg.UserId,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionWithId = `-- name: CreateSessionWithId :one
INSERT INTO
    "session" (
        id,
        token,
        "userId",
        "expiresAt",
        "ipAddress",
        "userAgent"
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, "userId", token, "expiresAt", "ipAddress", "userAgent", "createdAt", "updatedAt"
`

type CreateSessionWithIdParams struct {
	ID        uuid.UUID `json:"id"`
	Token     string    `json:"token"`
	UserId    uuid.UUID `json:"userId"`
	ExpiresAt time.Time `json:"expiresAt"`
	IpAddress *string   `json:"ipAddress"`
	UserAgent *string   `json:"userAgent"`
}

func (q *Queries) CreateSessionWithId(ctx context.Context, arg CreateSessionWithIdParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSessionWithId,
		arg.ID,
		arg.Token,
		arg.UserId,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :one
DELETE FROM "session" WHERE id = $1 RETURNING id, "userId", token, "expiresAt", "ipAddress", "userAgent", "createdAt", "updatedAt"
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, deleteSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM "session" WHERE "userId" = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userid)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, "userId", token, "expiresAt", "ipAddress", "userAgent", "createdAt", "updatedAt" FROM "session" WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, "userId", token, "expiresAt", "ipAddress", "userAgent", "createdAt", "updatedAt" FROM "session" WHERE token = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE "session"
SET
    token = $2,
    "userId" = $3,
    "expiresAt" = $4,
    "ipAddress" = $5,
    "userAgent" = $6,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, "userId", token, "expiresAt", "ipAddress", "userAgent", "createdAt", "updatedAt"
`

type UpdateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	Token     string    `json:"token"`
	UserId    uuid.UUID `json:"userId"`
	ExpiresAt time.Time `json:"expiresAt"`
	IpAddress *string   `json:"ipAddress"`
	UserAgent *string   `json:"userAgent"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.ID,
		arg.Token,
		arg.UserId,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
