// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_jwks.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getJwksSets = `-- name: GetJwksSets :many
SELECT
    id,
    "publicKey",
    "createdAt",
    "expiresAt"
FROM jwks
WHERE
    "expiresAt" IS NULL
    OR "expiresAt" > NOW()
`

type GetJwksSetsRow struct {
	ID        uuid.UUID  `json:"id"`
	PublicKey string     `json:"publicKey"`
	CreatedAt time.Time  `json:"createdAt"`
	ExpiresAt *time.Time `json:"expiresAt"`
}

func (q *Queries) GetJwksSets(ctx context.Context) ([]GetJwksSetsRow, error) {
	rows, err := q.db.Query(ctx, getJwksSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJwksSetsRow
	for rows.Next() {
		var i GetJwksSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicKey,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
