// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pay_events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO
    "events" ("userId", "type", "data")
VALUES ($1, $2, $3)
RETURNING
    id, "userId", data, type, "createdAt", "updatedAt"
`

type CreateEventParams struct {
	UserId uuid.UUID `json:"userId"`
	Type   string    `json:"type"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.UserId, arg.Type, arg.Data)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Data,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventWithId = `-- name: CreateEventWithId :one
INSERT INTO
    "events" (
        "id",
        "userId",
        "type",
        "data"
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, "userId", data, type, "createdAt", "updatedAt"
`

type CreateEventWithIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserId uuid.UUID `json:"userId"`
	Type   string    `json:"type"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateEventWithId(ctx context.Context, arg CreateEventWithIdParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEventWithId,
		arg.ID,
		arg.UserId,
		arg.Type,
		arg.Data,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Data,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, "userId", data, type, "createdAt", "updatedAt" FROM "events" WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Data,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByUserIDAndType = `-- name: GetEventByUserIDAndType :one
SELECT id, "userId", data, type, "createdAt", "updatedAt" FROM "events" WHERE "userId" = $1 AND "type" = $2
`

type GetEventByUserIDAndTypeParams struct {
	UserId uuid.UUID `json:"userId"`
	Type   string    `json:"type"`
}

func (q *Queries) GetEventByUserIDAndType(ctx context.Context, arg GetEventByUserIDAndTypeParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByUserIDAndType, arg.UserId, arg.Type)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Data,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByUserID = `-- name: ListEventsByUserID :many
SELECT id, "userId", data, type, "createdAt", "updatedAt" FROM "events" WHERE "userId" = $1 ORDER BY "createdAt" DESC
`

func (q *Queries) ListEventsByUserID(ctx context.Context, userid uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Data,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
