// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pay_subscriptions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO
    "subscription" (
        "userId",
        "externalId",
        tier,
        "cancelAtPeriodEnd",
        status,
        "currentPeriodEnd"
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type CreateSubscriptionParams struct {
	UserId            uuid.UUID  `json:"userId"`
	ExternalId        *string    `json:"externalId"`
	Tier              string     `json:"tier"`
	CancelAtPeriodEnd bool       `json:"cancelAtPeriodEnd"`
	Status            string     `json:"status"`
	CurrentPeriodEnd  *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserId,
		arg.ExternalId,
		arg.Tier,
		arg.CancelAtPeriodEnd,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionWithId = `-- name: CreateSubscriptionWithId :one
INSERT INTO
    "subscription" (
        id,
        "userId",
        "externalId",
        tier,
        "cancelAtPeriodEnd",
        status,
        "currentPeriodEnd"
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type CreateSubscriptionWithIdParams struct {
	ID                uuid.UUID  `json:"id"`
	UserId            uuid.UUID  `json:"userId"`
	ExternalId        *string    `json:"externalId"`
	Tier              string     `json:"tier"`
	CancelAtPeriodEnd bool       `json:"cancelAtPeriodEnd"`
	Status            string     `json:"status"`
	CurrentPeriodEnd  *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) CreateSubscriptionWithId(ctx context.Context, arg CreateSubscriptionWithIdParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscriptionWithId,
		arg.ID,
		arg.UserId,
		arg.ExternalId,
		arg.Tier,
		arg.CancelAtPeriodEnd,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :one
DELETE FROM "subscription" WHERE id = $1 RETURNING id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, deleteSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriptionByUserID = `-- name: DeleteSubscriptionByUserID :one
DELETE FROM "subscription" WHERE "userId" = $1 RETURNING id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

func (q *Queries) DeleteSubscriptionByUserID(ctx context.Context, userid uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, deleteSubscriptionByUserID, userid)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt" FROM "subscription" WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByPolarID = `-- name: GetSubscriptionByPolarID :one
SELECT id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt" FROM "subscription" WHERE "externalId" = $1
`

func (q *Queries) GetSubscriptionByPolarID(ctx context.Context, externalid *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByPolarID, externalid)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt" FROM "subscription" WHERE "userId" = $1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userid uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userid)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE "subscription"
SET
    "externalId" = $2,
    tier = $3,
    "cancelAtPeriodEnd" = $4,
    status = $5,
    "currentPeriodEnd" = $6,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type UpdateSubscriptionParams struct {
	ID                uuid.UUID  `json:"id"`
	ExternalId        *string    `json:"externalId"`
	Tier              string     `json:"tier"`
	CancelAtPeriodEnd bool       `json:"cancelAtPeriodEnd"`
	Status            string     `json:"status"`
	CurrentPeriodEnd  *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ExternalId,
		arg.Tier,
		arg.CancelAtPeriodEnd,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionByExternalID = `-- name: UpdateSubscriptionByExternalID :one
UPDATE "subscription"
SET
    tier = $2,
    "cancelAtPeriodEnd" = $3,
    status = $4,
    "currentPeriodEnd" = $5,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    "externalId" = $1
RETURNING
    id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type UpdateSubscriptionByExternalIDParams struct {
	ExternalId        *string    `json:"externalId"`
	Tier              string     `json:"tier"`
	CancelAtPeriodEnd bool       `json:"cancelAtPeriodEnd"`
	Status            string     `json:"status"`
	CurrentPeriodEnd  *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) UpdateSubscriptionByExternalID(ctx context.Context, arg UpdateSubscriptionByExternalIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionByExternalID,
		arg.ExternalId,
		arg.Tier,
		arg.CancelAtPeriodEnd,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionByUserID = `-- name: UpdateSubscriptionByUserID :one
UPDATE "subscription"
SET
    "externalId" = $2,
    tier = $3,
    "cancelAtPeriodEnd" = $4,
    status = $5,
    "currentPeriodEnd" = $6,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    "userId" = $1
RETURNING
    id, "userId", "externalId", tier, "cancelAtPeriodEnd", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type UpdateSubscriptionByUserIDParams struct {
	UserId            uuid.UUID  `json:"userId"`
	ExternalId        *string    `json:"externalId"`
	Tier              string     `json:"tier"`
	CancelAtPeriodEnd bool       `json:"cancelAtPeriodEnd"`
	Status            string     `json:"status"`
	CurrentPeriodEnd  *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) UpdateSubscriptionByUserID(ctx context.Context, arg UpdateSubscriptionByUserIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionByUserID,
		arg.UserId,
		arg.ExternalId,
		arg.Tier,
		arg.CancelAtPeriodEnd,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ExternalId,
		&i.Tier,
		&i.CancelAtPeriodEnd,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
